package middleware

import (
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	HTTPRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crossbow_http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "path", "status"},
	)

	HTTPRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "crossbow_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "path"},
	)

	SensorDataReceived = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crossbow_sensor_data_total",
			Help: "Total sensor data points received by crossbow",
		},
		[]string{"crossbow_id"},
	)

	AlertsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crossbow_alerts_total",
			Help: "Total alerts generated by crossbow and level",
		},
		[]string{"crossbow_id", "level"},
	)

	SimulationsRunning = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crossbow_simulations_running",
			Help: "Number of active simulation instances",
		},
	)

	RLTrainingActive = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_rl_training_active",
			Help: "Whether RL training is active for crossbow",
		},
		[]string{"crossbow_id"},
	)

	RLEpisodesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "crossbow_rl_episodes_total",
			Help: "Total RL training episodes",
		},
		[]string{"crossbow_id"},
	)

	RLRewardGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_rl_reward",
			Help: "Latest RL training reward",
		},
		[]string{"crossbow_id"},
	)

	RLEpsilonGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_rl_epsilon",
			Help: "Current RL exploration epsilon",
		},
		[]string{"crossbow_id"},
	)

	FireRateGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_fire_rate",
			Help: "Current fire rate (shots per minute)",
		},
		[]string{"crossbow_id"},
	)

	StringTensionGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_string_tension_newtons",
			Help: "Current string tension in Newtons",
		},
		[]string{"crossbow_id"},
	)

	StringFatigueGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_string_fatigue_ratio",
			Help: "Current string fatigue ratio (0-1)",
		},
		[]string{"crossbow_id"},
	)

	BowArmDeformationGauge = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "crossbow_bow_arm_deformation_mm",
			Help: "Current bow arm deformation in mm",
		},
		[]string{"crossbow_id"},
	)

	WSActiveConnections = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "crossbow_ws_active_connections",
			Help: "Number of active WebSocket connections",
		},
	)
)

func PrometheusMetrics() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		path := c.FullPath()

		c.Next()

		duration := time.Since(start).Seconds()
		status := strconv.Itoa(c.Writer.Status())

		HTTPRequestDuration.WithLabelValues(c.Request.Method, path).Observe(duration)
		HTTPRequestsTotal.WithLabelValues(c.Request.Method, path, status).Inc()
	}
}

func IncrementSensorData(crossbowID string) {
	SensorDataReceived.WithLabelValues(crossbowID).Inc()
}

func IncrementAlert(crossbowID, level string) {
	AlertsGenerated.WithLabelValues(crossbowID, level).Inc()
}

func SetSimulationsRunning(count int) {
	SimulationsRunning.Set(float64(count))
}

func SetRLActive(crossbowID string, active bool) {
	v := 0.0
	if active {
		v = 1.0
	}
	RLTrainingActive.WithLabelValues(crossbowID).Set(v)
}

func IncrementRLEpisodes(crossbowID string) {
	RLEpisodesTotal.WithLabelValues(crossbowID).Inc()
}

func SetRLReward(crossbowID string, reward float64) {
	RLRewardGauge.WithLabelValues(crossbowID).Set(reward)
}

func SetRLEpsilon(crossbowID string, epsilon float64) {
	RLEpsilonGauge.WithLabelValues(crossbowID).Set(epsilon)
}

func SetFireRate(crossbowID string, rate float64) {
	FireRateGauge.WithLabelValues(crossbowID).Set(rate)
}

func SetStringTension(crossbowID string, tension float64) {
	StringTensionGauge.WithLabelValues(crossbowID).Set(tension)
}

func SetStringFatigue(crossbowID string, fatigue float64) {
	StringFatigueGauge.WithLabelValues(crossbowID).Set(fatigue)
}

func SetBowArmDeformation(crossbowID string, deformation float64) {
	BowArmDeformationGauge.WithLabelValues(crossbowID).Set(deformation)
}

func SetWSConnections(count int) {
	WSActiveConnections.Set(float64(count))
}
